=== tradxxx/XML_Format/Project_xml/Project_xml/bin/Debug/net6.0/timesheet_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Определение элемента timesheet -->
  <xs:element name="timesheet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="day" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="tutorial" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="subject" type="xs:string" use="required"/>
                  <xs:attribute name="room" type="xs:string" use="required"/>
                  <xs:attribute name="teacher" type="xs:string" use="required"/>
                  <xs:attribute name="start" type="xs:string" use="required"/>
                  <xs:attribute name="end" type="xs:string" use="required"/>
                  <xs:attribute name="type" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== tradxxx/XML_Format/Project_xml/Project_xml/bin/Debug/net6.0/timesheet.xml
<?xml version="1.0" encoding="UTF-8"?>
<timesheet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="timesheet_schema.xsd">

  <day name="Понедельник">
    <tutorial subject="Практикум коучинг персонала" room="302" teacher="Антонова Н. В." start="11:10" end="12:30" type="практика"/>
    <tutorial subject="Практикум коучинг персонала" room="302" teacher="Антонова Н. В." start="13:00" end="14:20" type="практика"/>
  </day>

  <day name="Вторник">
    <tutorial subject="Психология межличностных отношений" room="209" teacher="Сариева И.Р." start="11:10" end="12:30" type="лекция"/>
    <tutorial subject="Психология межличностных отношений" room="209" teacher="Сариева И.Р." start="13:00" end="14:20" type="лекция"/>
  </day>

  <day name="Пятница">
    <tutorial subject="Технологии анализа данных в сети Интернет" room="online" teacher="Ланин В.В." start="07:40" end="09:00" type="практика"/> 
    <tutorial subject="Технологии анализа данных в сети Интернет" room="online" teacher="Ланин В.В." start="11:10" end="12:30" type="лекция"/>
  </day>

  <day name="Суббота">
    <tutorial subject="Анализ данных в HR" room="308" teacher="Титов А.С." start="09:30" end="10:50" type="практика"/> 
    <tutorial subject="Анализ данных в HR" room="308" teacher="Титов А.С." start="11:10" end="12:30" type="практика"/>
  </day>

</timesheet>
